### ISSUE TITLE
It can't run on expo web

### ISSUE THREAD

**Issue by MJRT** [Musta-Pollo/GridHabitTrackePublic#1]
Hi @Musta-Pollo, cool project, I try to understand for wa-sqlite how to run with expo-web

Trying to run `npx expo start -w` after clone and install, but web page is blank with error:
```
Error:  Error: sqlite3_open_v2
    at check (sqlite-api.js:857:11)
    at Object.open_v2 (sqlite-api.js:512:7)
    at async ElectricDatabase.init (database.js:59:16)
    at async initWaSQLite (config.ts:27:16)
    at async init (_layout.tsx:196:22)
```
Another version wa-sqlite also has error, do I need others setup?

v0.9.10-v0.9.14 has same error with `~0.9.8`;

v0.9.8 and v0.9,9 has error follow:
```
Error:  RuntimeError: memory access out of bounds
    at wa-sqlite-async.wasm:0x2d3b3
    at wa-sqlite-async.wasm:0x1d51
    at Oc.b.<computed> (wa-sqlite-async.mjs:52:126)
    at f._RegisterExtensionFunctions (wa-sqlite-async.mjs:101:353)
    at Object.Z [as ccall] (wa-sqlite-async.mjs:56:389)
    at Object.open_v2 (sqlite-api.js:511:14)
    at async ElectricDatabase.init (database.js:59:16)
    at async initWaSQLite (config.ts:27:16)
    at async init (_layout.tsx:196:22)
```

v1.0.0 and v1.0.1 has error:
```
Error:  RuntimeError: Aborted(LinkError: WebAssembly.instantiate(): Import #63 "a" "ja": function import requires a callable). Build with -sASSERTIONS for more info.
    at abort (wa-sqlite-async.mjs:8:4446)
    at wa-sqlite-async.mjs:8:5716

```

**Comment by MJRT** [comment]
ps: it's OK run on Android Expo Go after setup `ELECTRIC_URL`.
